service: contribute-to-open-source-lambda

package:
  exclude:
  - .circleci/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-1
  memorySize: 128
  timeout: 20
  environment: ${file(env.yml)}

functions:
  handleGitHubWebhook:
    handler: index.handleGitHubWebhook
    events:
      - http:
          path: hooks/github
          method: post
          integration: lambda
          cors: true
  handleCircleCIWebhook:
    handler: index.handleCircleCIWebhook
    events:
      - http:
          path: hooks/circleci
          method: post
          integration: lambda
          cors: true
  handleCleanupTask:
    handler: index.handleCleanupTask
    timeout: 60
    events:
      - schedule: cron(0 10 * * ? *)