service: contribute-to-open-source-lambda

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-ngrok-tunnel

package:
  exclude:
  - .buildkite/**
  - .github/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-1
  memorySize: 128
  timeout: 30
  environment:
    BUILDKITE_TOKEN: ${env:BUILDKITE_TOKEN}
    BUILDKITE_SECRET: ${env:BUILDKITE_SECRET}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    GITHUB_SECRET: ${env:GITHUB_SECRET}
    BUGSNAG_TOKEN: ${env:BUGSNAG_TOKEN}

functions:
  handleGitHubWebhook:
    handler: index.handleGitHubWebhook
    events:
      - http:
          path: hooks/github
          method: post
          integration: lambda
          cors: true
  handleBuildkiteWebhook:
    handler: index.handleBuildkiteWebhook
    events:
      - http:
          path: hooks/buildkite
          method: post
          integration: lambda
          cors: true
  handleHealthTask:
    handler: index.handleHealthTask
    events:
      - http:
          path: health
          method: get
          integration: lambda
          cors: true

custom:
  ngrokTunnel:
    tunnels:
      - port: 3000
        ngrokOptions:
          authtoken: ${env:NGROK_TOKEN}