service: contribute-to-open-source-lambda

package:
  exclude:
  - .circleci/**
  - .github/**

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-1
  memorySize: 128
  timeout: 20
  environment:
    CIRCLECI_TOKEN: ${env:CIRCLECI_TOKEN}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    GITHUB_SECRET: ${env:GITHUB_SECRET}
    BUGSNAG_TOKEN: ${env:BUGSNAG_TOKEN}

functions:
  handleGitHubWebhook:
    handler: index.handleGitHubWebhook
    events:
      - http:
          path: hooks/github
          method: post
          integration: lambda
          cors: true
  handleCircleCIWebhook:
    handler: index.handleCircleCIWebhook
    events:
      - http:
          path: hooks/circleci
          method: post
          integration: lambda
          cors: true
  handleCleanupTask:
    handler: index.handleCleanupTask
    timeout: 60
    events:
      - schedule: cron(0 10 * * ? *)