version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless
      - run:
          name: Deploy to AWS
          command: serverless deploy -v
      - run:
          name: Notify Bugsnag
          command: |
            curl https://build.bugsnag.com/ \
              --header "Content-Type: application/json" \
              --data '{
                "apiKey": "$BUGSNAG_TOKEN",
                "appVersion": "$(node -p "require('./package.json').version")",
                "builderName": "$CIRCLE_PROJECT_USERNAME",
                "sourceControl": {
                  "provider": "github",
                  "repository": "$CIRCLE_REPOSITORY_URL",
                  "revision": $CIRCLE_SHA1"
                }
              }'
      - save_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
