version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless
      - run:
          name: Deploy to AWS
          command: serverless deploy -v
      - run:
          name: Notify Rollbar of deploy
          command: |
            curl https://api.rollbar.com/api/1/deploy/ \
              -F access_token=$ROLLBAR_TOKEN \
              -F environment=production \
              -F revision=$CIRCLE_SHA1 \
              -F local_username=$CIRCLE_PROJECT_USERNAME
      - save_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
